import { FrameworkAdapter } from '../FrameworkAdapter.js';
import { AttributionQuality,CapabilitySupport,EvidenceLevel,FrameworkCapability,RuntimeEventType,summarizeRuntimeValue } from '../../core/evidence-protocol.js';
function _now(){return typeof performance!=='undefined'&&typeof performance.now==='function'?performance.now():Date.now();}function _isToken(v){return(typeof v==='object'&&v!==null)||typeof v==='function';}function _finiteOrNull(v){return Number.isFinite(v)?v:null;}function _sourceAttribution(s){return s?AttributionQuality.SOURCE_ATTRIBUTED:AttributionQuality.UNKNOWN;}function _instrumentedEvidence(s,l=EvidenceLevel.OBSERVATION){return{level:l,attribution:_sourceAttribution(s),confidence:s?0.9:0.7};}
class ReactAdapter extends FrameworkAdapter{
 #profilingEnabled;#correlationContext;#owners=new WeakMap();#physicalInstances=new WeakMap();#lifecycleGenerations=new WeakMap();#pendingRequests=new WeakMap();#instanceSequence=0;
 constructor(options={}){const profilingEnabled=options.profilingEnabled===true;super({...options,framework:'react',adapterVersion:'2.3',capabilities:{[FrameworkCapability.OWNER_LIFECYCLE]:CapabilitySupport.PARTIAL,[FrameworkCapability.UPDATE_LIFECYCLE]:CapabilitySupport.PARTIAL,[FrameworkCapability.UPDATE_CAUSE]:CapabilitySupport.UNSUPPORTED,[FrameworkCapability.STATE_CHANGE]:CapabilitySupport.PARTIAL,[FrameworkCapability.RENDER_TIMING]:profilingEnabled?CapabilitySupport.FRAMEWORK_REPORTED:CapabilitySupport.PARTIAL,[FrameworkCapability.SOURCE_LOCATION]:CapabilitySupport.PARTIAL,[FrameworkCapability.REACTIVE_DEPENDENCY]:CapabilitySupport.UNSUPPORTED,[FrameworkCapability.RESOURCE_OWNERSHIP]:CapabilitySupport.PARTIAL,[FrameworkCapability.EFFECT_LIFECYCLE]:CapabilitySupport.PARTIAL,...(options.capabilities||{})}});this.#profilingEnabled=profilingEnabled;this.#correlationContext=options.correlationContext||null;}
 get profilingEnabled(){return this.#profilingEnabled;}isManaged(t){return _isToken(t)&&!!this.#owners.get(t)?.connected;}
 #interaction(){return this.#correlationContext?.currentInteraction?.()||null;}
 connect(t,{name='react-component',source=null,parentId=null}={}){if(!_isToken(t))return null;const existing=this.#owners.get(t);if(existing?.connected){if(!existing.parentId&&parentId)existing.parentId=parentId;if(!existing.source&&source)existing.source=source;return existing;}let instanceId=this.#physicalInstances.get(t);if(!instanceId){instanceId=++this.#instanceSequence;this.#physicalInstances.set(t,instanceId);}const lifecycleGeneration=(this.#lifecycleGenerations.get(t)||0)+1;this.#lifecycleGenerations.set(t,lifecycleGeneration);const owner={id:`react-${instanceId}-life-${lifecycleGeneration}`,instanceId,lifecycleGeneration,kind:'component',name:String(name||'react-component'),parentId,connected:true,source};this.#owners.set(t,owner);this.#pendingRequests.delete(t);this.emit(RuntimeEventType.OWNER_CREATED,{owner,source,correlation:this.#correlationContext?.correlation?.(),evidence:{level:EvidenceLevel.OBSERVATION,attribution:AttributionQuality.FRAMEWORK_REPORTED,confidence:0.95},payload:{lifecycle:'effect-mounted',instrumented:true}});return owner;}
 linkParent(t,p){const owner=this.#owners.get(t),parent=this.#owners.get(p);if(!owner?.connected||!parent?.connected||owner.parentId===parent.id)return owner||null;owner.parentId=parent.id;this.emit(RuntimeEventType.DIAGNOSTIC,{owner,source:owner.source,correlation:this.#correlationContext?.correlation?.(),evidence:_instrumentedEvidence(owner.source,EvidenceLevel.ATTRIBUTION),payload:{diagnostic:'react.owner.parent-linked',parentOwnerId:parent.id,parentOwnerName:parent.name}});return owner;}
 disconnect(t,{source=null,reason='effect-cleanup'}={}){const owner=this.#owners.get(t);if(!owner?.connected)return null;owner.connected=false;this.#pendingRequests.delete(t);return this.emit(RuntimeEventType.OWNER_DESTROYED,{owner,source:source||owner.source,correlation:this.#correlationContext?.correlation?.(),evidence:{level:EvidenceLevel.OBSERVATION,attribution:AttributionQuality.FRAMEWORK_REPORTED,confidence:0.95},payload:{lifecycle:String(reason||'effect-cleanup'),instrumented:true}});}
 ownerOf(t){return this.#owners.get(t)||null;}
 recordUpdateRequested(t,{source=null,reason='instrumented-update',stateKey=null,oldValue=undefined,newValue=undefined,interactionId=null}={}){const owner=this.#owners.get(t);if(!owner?.connected)return null;const iid=interactionId||this.#interaction();const event=this.emit(RuntimeEventType.UPDATE_REQUESTED,{owner,source,correlation:iid?{interactionId:iid}:undefined,evidence:_instrumentedEvidence(source),payload:{reason:String(reason||'instrumented-update'),stateKey:stateKey==null?null:String(stateKey),oldValue:stateKey==null?undefined:summarizeRuntimeValue(oldValue),newValue:stateKey==null?undefined:summarizeRuntimeValue(newValue),sameReference:stateKey==null||oldValue===undefined||newValue===undefined?null:Object.is(oldValue,newValue),instrumented:true}});const pending=this.#pendingRequests.get(t)||[];pending.push(event.id);while(pending.length>20)pending.shift();this.#pendingRequests.set(t,pending);return event;}
 recordStateChange(t,key,oldValue,newValue,{source=null}={}){const owner=this.#owners.get(t);if(!owner?.connected||key==null)return null;const iid=this.#interaction();return this.emit(RuntimeEventType.STATE_CHANGED,{owner,source,correlation:iid?{interactionId:iid}:undefined,evidence:_instrumentedEvidence(source),payload:{property:String(key),oldValue:summarizeRuntimeValue(oldValue),newValue:summarizeRuntimeValue(newValue),sameReference:Object.is(oldValue,newValue),instrumented:true}});}
 recordProfilerRender(t,{id=null,phase='update',actualDuration=null,baseDuration=null,startTime=null,commitTime=null,source=null}={}){const owner=this.#owners.get(t);if(!owner?.connected)return null;const pending=[...(this.#pendingRequests.get(t)||[])];const iid=this.#interaction();const correlation={...(pending.length===1?{parentEventId:pending[0]}:{}),...(iid?{interactionId:iid}:{})};const event=this.emit(RuntimeEventType.UPDATE_COMPLETED,{owner,source,correlation:Object.keys(correlation).length?correlation:undefined,evidence:{level:EvidenceLevel.OBSERVATION,attribution:AttributionQuality.FRAMEWORK_REPORTED,confidence:1},payload:{profilerId:id==null?null:String(id),phase:String(phase||'update'),actualDurationMs:_finiteOrNull(actualDuration),baseDurationMs:_finiteOrNull(baseDuration),startTime:_finiteOrNull(startTime),commitTime:_finiteOrNull(commitTime),pendingRequestCount:pending.length,pendingRequestEventIds:pending,profilingEnabled:this.#profilingEnabled}});this.#pendingRequests.delete(t);return event;}
 createProfilerCallback(t,{source=null}={}){return(id,phase,actualDuration,baseDuration,startTime,commitTime)=>{try{return this.recordProfilerRender(t,{id,phase,actualDuration,baseDuration,startTime,commitTime,source});}catch{return null;}};}
 recordEffectStarted(t,effectId,{source=null,kind='effect'}={}){const owner=this.#owners.get(t);if(!owner?.connected)return null;return this.emit(RuntimeEventType.DIAGNOSTIC,{owner,source,correlation:this.#correlationContext?.correlation?.(),evidence:_instrumentedEvidence(source),payload:{diagnostic:'react.effect.started',effectId:String(effectId),effectKind:String(kind||'effect')}});}
 recordEffectCleanup(t,effectId,{source=null,kind='effect'}={}){const owner=this.#owners.get(t);if(!owner)return null;return this.emit(RuntimeEventType.DIAGNOSTIC,{owner,source,correlation:this.#correlationContext?.correlation?.(),evidence:_instrumentedEvidence(source),payload:{diagnostic:'react.effect.cleanup',effectId:String(effectId),effectKind:String(kind||'effect')}});}
 recordResourceAcquired(t,{resourceId,resourceType='unknown',source=null}={}){const owner=this.#owners.get(t);if(!owner?.connected||!resourceId)return null;return this.emit(RuntimeEventType.RESOURCE_ACQUIRED,{owner,source,correlation:this.#correlationContext?.correlation?.(),evidence:_instrumentedEvidence(source,EvidenceLevel.ATTRIBUTION),payload:{resourceId:String(resourceId),resourceType:String(resourceType||'unknown'),instrumented:true}});}
 recordResourceReleased(t,{resourceId,resourceType='unknown',source=null}={}){const owner=this.#owners.get(t);if(!owner||!resourceId)return null;return this.emit(RuntimeEventType.RESOURCE_RELEASED,{owner,source,correlation:this.#correlationContext?.correlation?.(),evidence:_instrumentedEvidence(source),payload:{resourceId:String(resourceId),resourceType:String(resourceType||'unknown'),instrumented:true}});}
 createEffectBridge(t,effectId,{source=null,kind='effect'}={}){return Object.freeze({start:()=>this.recordEffectStarted(t,effectId,{source,kind}),cleanup:()=>this.recordEffectCleanup(t,effectId,{source,kind})});}
 createCapabilityResolver(){return(f,c)=>f==='react'?this.capability(c):CapabilitySupport.UNSUPPORTED;}
 diagnosticsSnapshot(t){const owner=this.#owners.get(t),pending=this.#pendingRequests.get(t)||[];return Object.freeze({ownerId:owner?.id||null,parentId:owner?.parentId||null,connected:!!owner?.connected,lifecycleGeneration:owner?.lifecycleGeneration??null,pendingUpdateRequests:pending.length,capturedAt:_now()});}
}
const reactAdapter=new ReactAdapter();export{ReactAdapter,reactAdapter};
